"""link stock and user tables

Revision ID: 497e558d5239
Revises: f14f75339e9d
Create Date: 2024-10-15 06:44:54.940097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497e558d5239'
down_revision = 'f14f75339e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_stocks_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stocks_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
